{% set version = "0.1.4" %}
{% set sha256 = "2f191432d32b05d52f546d873c43278d2d87a06af54dda388ce9deeb879150bf" %}

package:
  name: lazyasd
  version: {{ version }}

source:
  fn: lazyasd-{{ version }}.tar.gz
  url: https://github.com/xonsh/lazyasd/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - lazyasd
  requires:
    - pytest
  commands:
    - py.test

about:
  home: https://github.com/xonsh/lazyasd/blob/master/README.rst#lazyasd
  license: BSD 3-clause
  summary: 'Lazy & self-destructive tools for speeding up module imports'
  description: |
    A package that provides lazy and self-destructive tools for speeding up module imports.
    This is useful whenever startup times are critical, such as for command line interfaces
    or other user-facing applications. The tools in this module implement two distinct
    strategies for speeding up module import. The first is delayed construction of global
    state and the second is to import expensive modules in a background thread.
  doc_url: http://xon.sh/api/lazyasd.html
  dev_url: https://github.com/xonsh/lazyasd

extra:
  recipe-maintainers:
    - scopatz
