travis:
  secure:
    BINSTAR_TOKEN: yu22qaJ03siJF5Ls/Lfjpr6d7TgxYYIufnFuieRsmPmn+2rELHcw0sjB9mdJZw83Azsw/nEEYhYHEzt0VoCGlbgGOJbGM0GqaLEVOE7wiUclTPjxcqflYxbNjGiRfJYcNFXXTBooggW8EygnZpfFOWKLPhHbt+W80k6rk2rf2cFX+MHWIQfy6Hq4feEzaJeHr5eCH2VW8/krhRxvMs9tpF1cIEJnQ45ZKJuD+oKk5jBEFqyBD53eWZyrUW4MmMlp5prb0vKgnSBS+Zt2mNTKfu8j9eje+K6sK4HvTadtsa+qNNBC+DZoCxYg4ln/BKXQg1b8Fku6dWIjJxI9Ior2qcvEbV1T+gbSRxrTeS+DdlmNvFZo0n6FApeecTJRH9Hv7IpKCWZJo9LKG5OQA71UguIOMMNyCV8L1sIewqtpf5yxjxAxcwcdPrV6l1fiMprO/2L7CPFdX+ehljrpVj5ucx+qpidI7pTvnOtezgEVZxOUFTdHBHYW8GvS8rmTHGnvwsAVvYIyYplM7BV5tZ196fgCWQY4vxA85TK3etDBM3EpfDxL7xfLbzgVFFgFtEdjlLz5EqHDe1W6+cQbPruWQs84TEAMFibvtMPyFLFHcrdBcqalK+woWGp4U0xCCs/9R135PSSqzIe9ozwSsGVW2nDWy3yskVN7siSWsqfuuHA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
