travis:
  secure:
    BINSTAR_TOKEN: d1eM7yMfmv1WFI9wcya+ujGaiJuEux36pEJGXXQZKS0b6oTm8WHtHvyeSOv069gyWNkT0DZAgVF+XvTgQtEOnEdRemXfKP81FNatuKYXoBlA1m/VQhB6RMZsCT7fQVbNuUDscvjnPlvGde/xkXZ1cozWtoJM6ZMq8E3pVKxSvyVJkS0sW1aruBMmc0RT2Ry+p7/lpkuWoxI1f76f39ys1IqT6HEdVl8BX8HXLHk8vsdqW9RjBvK6tHUhip7plgz5JcJAJJsKXC9X7FmFU04DrnocLRv6Jck0xD+jjcPtZQCXlu+jpr4J7j3G/vO4T6hZkoqztt58gPWi413rXfbjGV7Q1j4mv+8l4HKhx6T8Z1mUIBhLeZRgSwMFb4qhYvLeJ+TWVXrzi48SmaNUeNelqpsE5z7vestKCzdOVuRkFidfYuWZpPqcKIq63f8q3fTtayAaoIHjz2ORFdqruzjFepZyZugn9uq3kbBiZllSyy1yetsd730rIvKTg+5q+zDvU000fc68xf6b8keSme5B3gC5Dtew6l8MnkPjRoOPe2qM2/mGd/feivl9W/0DS/3QXywLw1GWVb/wRXrQom+MaVh5Avs/8Vd6Ngp3HUPhzLzpIw7G7vPkyyhd14f6mf5DgYLeRvQW9bMskayQ1hICT6b/D5wuOw9YxnWxm6xdjbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
